<?php
/**
 * Страница "Форма настроек рабочего пространства".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Workspace settings form</h1>
    <p>The settings form can be called from:</p>
    <ul>
        <li>web application configuration panel;</li>
        <li>partition bar "Configuration / Interface";</li>
        <li>start, item "Configuration".</li>
    </ul>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Reset settings.</b> Resets all settings to default values (only after pressing the "Save" button).</li>
    </ul>

    <h3>Main menu</h3>
    <p>The main workspace menu has the following setting fields:</p>
    <ul class="g-help-list">
        <li><b>Show main menu.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>

    <h3>Tray bar</h3>
    <p>The workspace tray bar has the following customization fields:</p>
    <ul class="g-help-list">
        <li><b>Show panel.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>

    <h3>Partition bar</h3>
    <p>The workspace partition bar has the following customization fields:</p>
    <ul class="g-help-list">
        <li><b>Show panel.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Panel position.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>

    <h3>Navigation bar</h3>
    <p>The workspace navigation bar has the following customization fields:</p>
    <ul class="g-help-list">
        <li><b>Show panel.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Ability to collapse the panel.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li>
        <li><b>Ability to stretch the panel.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Panel width, px.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Panel position.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>
</article>