<?php
/**
 * Страница "Форма настроек рабочего пространства".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма настроек рабочего пространства</h1>
    <p>Форму настроек можно вызвать из:</p>
    <ul>
        <li>панели конфигурации веб-приложения;</li>
        <li>панели разделов "Конфигурация / Интерфейс";</li>
        <li>пуск, пункт "Конфигурация".</li>
    </ul>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><b>Сбросить настройки.</b> Сбрасывает все настройки до значений по умолчанию (только после нажатия кнопки "Сохранить").</li>
    </ul>

    <h3>Главное меню</h3>
    <p>Главное меню рабочего пространства имеет следующие поля настройки:</p>
    <ul class="g-help-list">
        <li><b>Показать главное меню.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>

    <h3>Панель уведомлений</h3>
    <p>Панель уведомлений рабочего пространства имеет следующие поля настройки:</p>
    <ul class="g-help-list">
        <li><b>Показать панель.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>

    <h3>Панель разделов</h3>
    <p>Панель разделов рабочего пространства имеет следующие поля настройки:</p>
    <ul class="g-help-list">
        <li><b>Показать панель.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Позиция панели.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>

    <h3>Панель навигации</h3>
    <p>Панель навигации рабочего пространства имеет следующие поля настройки:</p>
    <ul class="g-help-list">
        <li><b>Показать панель.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Возможность свернуть панель.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li>
        <li><b>Возможность растянуть панель.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Ширина панели, пкс.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam;</li> 
        <li><b>Позиция панели.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.</li> 
    </ul>
</article>